### ISSUE TITLE
Social Facebook event/page always reports invalid value

### ISSUE THREAD

**Issue by DHLSmith** [camdram/camdram#1721]
I tried variations of @impronuats, impronauts, https://www.facebook.com/impronauts, facebook.com/impronauts.
All report "This value is not valid."
Am I doing it wrong? Thank you.

**Comment by CHTJonas** [comment]
Oooh this does look like a bug - nice catch, thanks! I haven't looked at the code but I suspect the validation is expecting a numeric ID (i.e. https://www.facebook.com/24183295566) rather than a URL slug (i.e. https://www.facebook.com/impronauts/) and that's what's causing the error here.

In the meantime, while we get the underlying issue sorted, I've manually set it for 'Keeping Up with the Kimprov'.

**Comment by DHLSmith** [comment]
Thank you!

**Comment by hoyes** [comment]
I recently received an e-mail from Facebook saying that they've disabled the Camdram dev app because they need further information on our usage of the API... I've also just discovered that I'm the only admin for the Facebook app so I've just fixed that too.

The error message from the Facebook API for this is:

> Object does not exist, cannot be loaded due to missing permission or reviewable feature, or does not support this operation. This endpoint requires the 'manage_pages' or 'pages_read_engagement' permission or the 'Page Public Content Access' feature or the 'Page Public Metadata Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages, https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS and https://developers.facebook.com/docs/apps/review/feature#page-public-metadata-access for details.

Investigating what we need to do to fix this.

**Comment by DHLSmith** [comment]
Ok. Thank you.
I suppose if no one else is using it, one option is just to remove the
feature from Camdram!
Good luck, and thank you for providing this service
