### ISSUE TITLE
Create method of retrieving show posters from API

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#185]
This could be easily done by making /shows/[show-slug]/image_w123_h234.jpg redirect to the actual image URL. Alternatively include in the API data.

**Comment by chrisjamesnash** [comment]
The 'image' field now seems to have disappeared. Has this been implemented in a different way or has it just been left off?

**Comment by philosophicles** [comment]
I can confirm there's no image field on a random current show's xml endpoint (a show that does have an image uploaded to Camdram). 

I'm not aware, from general monitoring of GitHub activity, of any deliberate attempt to change this. Therefore let's assume for now this is a regression, until someone proves otherwise. 

Note @chrisjamesnash, one of the main developers is away this week so do please be patient for a response :)

**Comment by philosophicles** [comment]
I'll go one further and say that the one-line change to Show.php in commit df94d5a (adding `@Serializer\Expose()` - which I presume was the magic blue smoke for this) was removed again (presumably by accident) in a4ff256. @hoyes can you have a quick look and confirm if there was a reason for this?
