### ISSUE TITLE
Homepage news feed can be very long

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#220]
The news feed is fine as it is, but it can be quite long - currently well over twice as long as the left hand column for 'Get Involved', 'This time...' etc.  

Might be more visually balanced if it was limited to the same height on-page as the left-hand column, or perhaps could scroll within a smaller frame (either scroll-bar for user to use, or an auto-scrolling widget).

**Comment by GKFX** [comment]
This could be resolved by making the newsfeed items flow better, i.e. filling the currently empty space in the left column. That avoids the asymmetry and reduces the scrolling without actually cutting content. (Of course increasing or decreasing the amount of content is a discussion that can be had too.)

CSS has improved quite a bit since Camdram v2 first came out so there should be some aesthetically pleasing solution to be found. I might have a go at it once multiple societies is working, but since that's a long job I won't self-assign as yet.

**Comment by CHTJonas** [comment]
Looks good imo!
