### ISSUE TITLE
GMail one click actions

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#241]
![image](https://cloud.githubusercontent.com/assets/2594055/4999838/9674bcf6-69dd-11e4-94f7-929792de91a7.png)

Not high priority by any means, but we could add support for 'one click actions' in GMail for our notification emails, e.g. to go to a show page to authorize a show without having to open the email.

Docs: https://developers.google.com/gmail/markup/actions/actions-overview#one-click_action

**Comment by dstansby** [comment]
I've made a start to this here: e56f45c28abfdff915661c536d04b4446a5985e9

- It *should* send a html version that has a fallback plain text version for those who can't view html emails (see http://swiftmailer.org/docs/messages.html#setting-the-body-content)
- In order to test it, an email needs to be sent from a gmail address to the same gmail address (https://developers.google.com/gmail/markup/testing-your-schema) - I'm not too sure how to achieve this to test it properly from camdram?
- Eventually camdram needs to register with google to do this properly (https://developers.google.com/gmail/markup/registering-with-google), but I imagine that's quite far down the line!

**Comment by hoyes** [comment]
I hadn't twigged (no pun intended) this would require HTML emails, but seems like a nice idea (bonus points for prettifying them at some point). One thing: remove the {%autoescape%} tags from the HTML version (Twig automatically escapes data in templates by default to help prevent XSS issues, but this had to be turned off for the plain text version). Otherwise HTML emails look good.

In app_dev mode, all emails sent by script are diverted to whatever is defined in app/config/parameters.yml mailer_delivery_address. If you set up the other mailer_ parameters to point to your gmail account then it will automatically cause all emails to be sent to yourself (Swiftmailer adds X- headers which you can view in GMail to confirm where the email would have been sent).

Re your third point, there are a couple of things in that link that may be problematic:
 *  Emails must be authenticated via DKIM or SPF - probably do-able but I don't know exactly what this involves
 * "Consistent history of sending a high volume of mail from your domain" - I imagine we don't send 100 emails a day to GMail.
From the second point, it looks uncertain as to whether Google would accept us. It looks like the main work involved here is making emails HTML though, which would be a nice thing to have anyway, so if you're still happy to do this work and add the relevant JSON then we can take a gamble with registering.

**Comment by dstansby** [comment]
Thanks for the quick reply! I'll have a play around in my branch at some point over the next couple of weeks and try and get at least HTML emails working on my local copy.

**Comment by CHTJonas** [comment]
@dstansby Hi David! Long time ago and you've probably lost your WIP but how far did you get with this issue?

**Comment by philosophicles** [comment]
FWIW @alexbrett added an SPF record very recently (June 2018) for mostly unrelated reasons - so that part is done now. 

I just looked at the raw version of a recent "New show needs authorisation" email and we do appear to have the relevant markup in the email so I guess that was part of @dstansby 's PR #265 :
<img width="580" alt="screen shot 2018-07-15 at 4 13 10 pm" src="https://user-images.githubusercontent.com/5232616/42739322-17943670-884a-11e8-92a8-83989353398e.png">

David please do chip in with your understanding - but just in case you're busy / not checking GitHub for ages: my interpretation is that the coding for this is done and it's more about the bureaucracy / box-checking to make this work. 

However I echo @hoyes earlier concerns, it looks like the requirement `Consistent history of sending a high volume of mail from your domain (order of hundred emails a day minimum to Gmail) for a few weeks at least.` may be a complete showstopper for this. :-(

**Comment by GKFX** [comment]
Closing as can’t fix; we don’t send enough emails. If Google’s policies change we can re-open but it seems unlikely.
