### ISSUE TITLE
Society/venue of shows not linked to society/venue object

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#243]
A few shows have been added with venue text e.g. 'ADC Theatre', but without being linked to the corresponding venue object. Hard to tell why - maybe people don't spot the autocomplete drop-down.

Perhaps we just need to do an extra check for this after form submission.

**Comment by hoyes** [comment]
Also applies for performance venue fields.

NB room booking uses performance venid to work out shows that are eligible for room booking...

**Comment by alexbrett** [comment]
Just happened again (support request 75347) - perhaps we need a check which if the entered text is identical to a given option (preferably ignoring case) either automatically associate or display a confirmation option.

**Comment by philosophicles** [comment]
It looks like the first matching option in the list isn't autoselected (no yellow background unless you mouseover).  Perhaps it's to do with that?

A 'Press enter/tab to complete' kind of hint near the textbox (while that textbox is active) might also help - we're all used to tab completion but this isn't so intuitive to non-techie users.  (NB Enter doesn't work currently because of lack of autoselect.)

Another visual cue could be a green tick icon next to the textbox when they successfully link to a venue/show object.  Versus perhaps some kind of 'warning' icon (orange exclamation mark?) if not linked, with some mouseover text explaining what the problem is.

Another way of approaching this altogether might be to take a default stance of 'you can only pick one of the existing options' - the text entry acting more just as a search box to filter a list of options? This would probably require changing the current form controls substantially though.  

There'd be an option somewhere of "[Society/Venue] not listed? Enter below or contact us to set up a new [society/venue] registration." A freetext entry box would only be visible when this option was selected.

**Comment by hoyes** [comment]
It now:
 * If the hidden field contains an id, checks that both the id and name fields match the DB
 * Otherwise do a search for the submitted name
 * Also changed the javascript function which populates the hidden field to use the 'autocompleted' event rather than the 'selected' event, which only fires when you click on an item in the list.
