### ISSUE TITLE
Search for new show admins by name

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#249]
Currently one has to know the email address of someone who you want to add as an admin for a show. Might be nice if you could search for a name and add by name?

**Comment by ajf58** [comment]
Agreed. I think we'd need to ensure that in doing so the email address of the person wasn't made visible to the searcher, e.g. if you type Joe Bloggs then it doesn't make Joe Bloggs' email visible to you.

**Comment by philosophicles** [comment]
I think I missed this first time around. As per @hoyes comments on #255 I don't think this is such a great idea. 

* Firstly because of the practical name-disambiguation/variation challenges (two people called Joe Bloggs; a person officially called Joseph Bloggs who might be Joe or Joseph (or Jo, Seph, etc) on Camdram) - exactly as @hoyes noted.

* Secondly because if you don't know the person's email (de facto unique human identifier for the internet) and can't easily ask them for it, should you be adding them as a trusted admin of anything?

**Comment by CHTJonas** [comment]
Ok - closing this issue in favour of #255 for the reasons surmised above 👆
