### ISSUE TITLE
SocID points to venue

### ISSUE THREAD

**Issue by sigilion** [camdram/camdram#276]
The shows with the following slugs cause the server to 500, as their socid field points to a venue in the societies table, which camdram can't deal with:
2001-electra
2003-coriolanus
2003-troilus-and-cressida
2005-vigani-s-cabinet-sprung
mastana-2005
2005-impromime
2009-the-importance-of-being-earnest

I've left a bookmarked sql query on phpMyAdmin.

**Comment by hoyes** [comment]
I'd say that given that these are all quite old shows, it's probably safe to assume that this was caused by an old bug, so it should be sufficient to just these rows in the database somehow (by null-ing them if we can't make sense of the IDs). Hopefully we can separate out societies and venues into separate tables in the not-too-distant future...

**Comment by ajf58** [comment]
Fixed. In most cases the society and venue were muddled up.
