### ISSUE TITLE
Add RSS feeds for non-techie vacancy types

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#295]
#91 achieved feature parity with V1 in terms of RSS.

However V1 never had RSS feeds for auditions, producer/director roles or show applications. I think RSS was originally sufficiently geeky and niche that people assumed non-techies probably wouldn't use it.

However, RSS is pretty universal these days - certainly not everyone uses/knows about it but I think actors, directors & producers are perfectly likely to use it already.

So it might be worth extending our RSS feed offering at some point.

**Comment by philosophicles** [comment]
MIght have a dependency on #159 (depending how drastic the vacancies rewrite is).

**Comment by dstansby** [comment]
Currently having a go at this here: https://github.com/camdram/camdram/compare/master...dstansby:rss?expand=1

The database rebuilds fine, and I can run a local server, but going to vacancies/auditions.rss just redirects me to vacancies/auditions. Does anyone know what I'm missing to get the RSS to show up?

**Comment by hoyes** [comment]
Can't see anything obvious ...will have a proper look this evening

**Comment by hoyes** [comment]
I've just checked out your branch and there are 2 immediately problems I can find:
 * I see you've created a 'last_updated' field in Audition. In a world where we didn't have to maintain backward compatibility with v1 this would be fine, but unfortunately at the moment we can't really add this as it won't be set if someone creates an audition in v1. I'm guessing you only added this because it's called by getFeedTitle() though - simplifying the feed title should make that error go away
 * At the moment there isn't a 'get_audition' route (because they're all rendered on one page). I solved this for techie adverts by creating a 'get_techie_advert' route that simply redirects to 'get_techies' with a hash url (so it jumps to the right point on the page). It should be straightforward to do the same thing for auditions, but do ask if you need a further pointer. If you do this, it would be nice to do a search for other links to individual auditions (from the home page and show pages), and update these to use the 'get_audition' route.

Also, at the moment, it'll complain that it can't find a 'created_at' and 'updated_at' field on Auditions. Looking at the RSS spec though, these aren't actually required, so I'll push an update soon which will make this error go away (I'll post here when I've done it so you can update).

**Comment by hoyes** [comment]
The commit above makes the 'updated_at' field optional

**Comment by dstansby** [comment]
Thanks, I now have this all working, and just need to finish adding the content now, which I'll probably do tomorrow.

**Comment by dstansby** [comment]
All seems to be working, apart from the RSS title links aren't being generated properly. Clicking on one throws the exception here: https://github.com/camdram/camdram/blob/9719b2e0797b5b401021275776c2a82002fcfb4b/src/Acts/CamdramBundle/Controller/AuditionController.php#L50

... which makes me suspect that findOneShowBySlug that I've made here isn't working properly:

https://github.com/camdram/camdram/blob/9719b2e0797b5b401021275776c2a82002fcfb4b/src/Acts/CamdramBundle/Entity/AuditionRepository.php#L119

**Comment by hoyes** [comment]
You could try doing 
    var_dump($identifier);
    die();
in the controller to see what identifier it's actually getting passed in. If that looks alright, try paring back the query in findOneByShowSlug to just the slug where term and gradually add clauses back to what's breaking things

**Comment by dstansby** [comment]
The $identifier being handed to getAction is non-sesnsical (ie. just a number, not the slug in a string). I'm not too sure where getAction is called from though...

**Comment by dstansby** [comment]
Nevermind, I seem to have fixed this. Because Entitiy/Audition.php didn't have a getSlug method, for some bizarre reason instead of throwing an error somewhere along the way a number was just used instead of the slug.

**Comment by dstansby** [comment]
Whew, almost there!

It's all working now, apart form one thing: trying to click some (but not all) title links in auditions.rss throws a NonUniqueResultException when calling getOneOrNullResult() here:

https://github.com/camdram/camdram/blob/070a84ecfe1375a3daeb6740b5b68065ab72cd21/src/Acts/CamdramBundle/Entity/AuditionRepository.php#L131

I'm not sure what's causing this; there doesn't obviously seem to be any non-unique shows to find.

**Comment by hoyes** [comment]
I suspect it's because it's actually searching for 'Audition' objects not 'Show' objects. Auditions have one row per audition session, so I'm guessing you're getting a NonUniqueResultException when there are more than one planned audition session for a show.

The simplest solution, given that the name of the function is ''findOneByShowSlug", would probably be to add a '->setMaxResults(1)' to the query
