### ISSUE TITLE
jsonp booking links

### ISSUE THREAD

**Issue by chrisjamesnash** [camdram/camdram#296]
I've been trying to add booking links to the G&S website using the jsonp feed from Camdram, but either something is missing or I'm doing it wrong. I have used the booking_code field as for The Sorcerer http://www.camdram.net/shows/2015-the-sorcerer-at-the-minack this contains the booking link. However although the Grand Duke http://www.camdram.net/shows/2015-the-grand-duke has a booking link on Camdram, there is no booking_code in the jsonp feed. Is booking_code different to the booking link, and could the booking links be added to the jsonp feed?

**Comment by hoyes** [comment]
Sorry for the delay.

The short answer is that the correct DB field is actually 'online_booking_url' not 'booking_code', but that isn't currently exposed via the API.

The long answer: when doing the show edit form in v2 (and clearly also the API) I initially misinterpreted the db fields and made the 'online booking url' field map to the 'booking_code' field. This was later fixed (and booking_code fields were copied across to online_booking_url fields), but it does mean that some booking_code fields now have urls in them. 'booking_code' I think is a legacy field from a day when the ADC website show pages were of a form 'www.adctheatre.com/show.php?showid=??' or something, so it used it to auto-generate a URL. It probably shouldn't be exposed any more.

I'll change it so that 'booking_code' is hidden in the API and 'online_booking_url' is exposed.

**Comment by philosophicles** [comment]
Ghost of seasons past: @hoyes is correct about `bookingcode` and the old ADC Theatre website. It was a rather ADC Theatre-specific feature / data item.  Since we're not displaying it anywhere in the new website and it wouldn't help if we did (because ADC Theatre website moved on) we should probably delete it altogether when V1 is retired.
