### ISSUE TITLE
Creating user with name containing only non [A-z] characters results in empty slug.

### ISSUE THREAD

**Issue by dtwood** [camdram/camdram#302]
The slug generator function currently works by removing all non-latin characters, and the replacing spaces with hyphens. Therefore changing a user's name to include only non-latin characters results in them having an empty slug, which doesn't appear to be possible to change back fully without DB access.

I've had a look at fixing this, but there's only one place where `setSlug` is actually called on a person's name, and that's in show creation code, which I can't run. The rest of the time Symphony auto generates it from the name (`src/Acts/CamdramBundle/Entity/Person.php:58`). So unless anyone who actually knows php has any ideas, I think this is something that we'll need to fix upstream in Gedmo/Sluggable.

**Comment by philosophicles** [comment]
Just to be clear, is this 'what if' type thinking or have we got a real scenario of a user who wishes their Camdram name to be solely [^A-z]? (technically [^A-9] I suspect?)

I suspect if we're doing this, we should apply the same flexibility to show slugs.

**Comment by dtwood** [comment]
Mainly that I was curious, and tried. Which resulted in Jamie having some fun trying to change my name back. So there's currently a user named ᴀ in the database, which he can't get rid of, and it's impossible to have another user called David Wood. If someone is willing to give me database access, then I'm happy to try and fix the mess I've created.

I was intending to add some `if ($slug='') return;` style statements around calls to getSlug, to at least stop people breaking the database again, but I can't actually figure out a way to do that.

**Comment by hoyes** [comment]
Given that a primary requirement for a name is that it's pronounceable, I
would suggest that we simply do better validation of the name field (e.g.
has at least 4 Roman characters and a space in the middle somewhere).

Slugs are inserted into an object automatically just before persisting by a
listener which detects a blank slug or name change. It is possible to write
a custom slug generator (shows have one of these to insert the year), but
I'm not sure what the best solution would be for such names.

The only situation I can think of where this might be a genuine problem is
for names in non-Roman script (Chinese, Arabic) etc. But even then most end
up using an Anglicised name in Western countries so I don't think this is a
massive issue. I believe the baked in slug generator does converted
accented characters to their non-accented counterparts.

**Comment by philosophicles** [comment]
I think there is a valid argument for (much longer-term / later / if somebody specifically wants to work on it as a pet project) supporting names in non-Roman script. 

In the shorter (more realistic) term I agree adequate validation is a better approach, but "pronounceable" is totally subjective which makes it difficult in practice. (See http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/).  E.g. Single letter 'O' is apparently a common Korean surname, I know people with surname 'Ng', and single-letter given names are entirely legal in the UK (though discouraged - but somebody might want to use a common-name rather than legal name on Camdram, which is fair enough). Similarly, whilst legally you need a forename and surname in the UK, a few people do use a single name as their common name so 

Given all that, if we do add any validation, I'd suggest just "at least one Latin character (regular or modified/accented)" as a bare minimum to ensure no empty slugs. I presume Names also get the -1, -2 suffixes if required to differentiate different people...?

Furthermore, since this isn't a 'real' user need, just @dtwood being a typical curious Cambridge student (:-p), I'm inclined to say actually let's do nothing other than fix his record.

**Comment by philosophicles** [comment]
Having just had a look at phpMyAdmin, to clarify, this whole issue is about `Person` __not__ `User` names.  (The object associated to involvement in shows, not logging-in to Camdram.)  The two terms had been used interchangeably above now I re-read, but I'd mentally assumed we were on about users. Don't know if that was just me...

It appears that when @dtwood changed the name of his Person record, it actually changed his slug to `NULL` not empty string. I have manually edited both the `name` and `slug` fields back to what (I assume) they were before. I imagine the search cache will catch up with this in due course. However, @dtwood's Person appears not to be associated to any shows, which I suspect has something to do with the NULL and foreign keys...?

**Comment by dtwood** [comment]
I'm not actually associated with any shows because of Jamie's failed attempt to fix me - he made a new version of me, and then added that to all the shows, and found he couldn't actually then rename it properly. My main person entry should be that with id 47723, and he's created a new one with id 66003.

**Comment by dtwood** [comment]
There also seems to be another one with id 65998 now, not a clue what that is.

**Comment by philosophicles** [comment]
Where are you getting these ids from? The highest id currently in our person table is less than 14000...

**Comment by dtwood** [comment]
those are from the autocomplete json (eg. http://www.camdram.net/search/autocomplete.json?q=david+wood&limit=10&autocomplete=true), which do appear to be different to those in old camdram.

**Comment by philosophicles** [comment]
I suspect those are Sphinx-internal keys if they're to do with search/autocomplete. "Sorry mate, that's not our database...".

**Comment by dtwood** [comment]
Yup, probably, I just didn't know any other way to get ids from new camdram. I believe that, now that David Wood exists, you should be able to fix it by merging that person with the D Wood that Jamie created.

**Comment by dtwood** [comment]
OK, so from the XML files, we have 9544 (the correct one), and 13200 (the new one that Jamie made, with the wrong name, that the shows are associated to).

**Comment by philosophicles** [comment]
WOrking on it

**Comment by philosophicles** [comment]
Give it a while for Sphinx to update (I think it's hourly?) then I think it should all work now. I have got no idea what Jamie did here - any chance you could get him to explain?

**Comment by dtwood** [comment]
Jamie said earlier that: "i shall leave you as d wood... then you need to delete 13199, add a david wood to a show so that a new person is created with the correct slug, then merge d wood into that new person.", if that helps you.

A suggestion, although I have no idea how to use PHP so can't really implement it, would be to use PHP's built in transliterator, to simplify the name first in the custom slug handler - http://php.net/manual/en/transliterator.transliterate.php. Although my head hurts from all this Unicode, and PHP's definitely not going to help, so I'm going to call this a night now.

**Comment by stumo** [comment]
We can probably just make sure that names have at least one printable
character, and with the right regular expression that will include foreign
scripts. Likewise for anything else that can have a slug. Potential
attackers will try this so worth fixing.

**Comment by philosophicles** [comment]
After another round of faff this morning, @dtwood, I have fixed your record fully. Please don't try experimental things on the live database again! 

Also, in future, it's probably better to deal with such things via email to websupport@camdram.net, this issue is now rather cluttered with non-development stuff.

I will leave others to decide whether any actual development work is worth doing in this area.

**Comment by ajf58** [comment]
I'd like to emphasise @philosophicles request. This really is low-value bug reporting. Closing this as a "won't fix" issue, as there is no requirement for it and valid alternatives have been suggested.
