### ISSUE TITLE
Diary - year dropdown includes 2016 but no terms for 2016

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#326]
Currently, from the diary page, I can select the year 2016. When I do so, the second dropdown (intended to pick a specific term) is empty i.e. no options to pick from. 

I'm not totally sure how this is driven. It doesn't look like it's driven by acts_termdates table (which V1 used) because that has no entries past Mayweek 2015. If it IS somehow driven by acts_termdates, then there's a side issue here that V2 needs the ability to edit acts_termdates (as V1 does) or some other way of populating acts_termdates (scraping the Uni website? ;-) ). This would be a feature-parity, Laurie, issue - so I'm assigning to Laurie until someone says otherwise.

Regardless, I think a year shouldn't be available in the drop-down without at least one term being selectable for it. And presumably the presence of anything in each dropdown should be governed by the existence of at least one end-user-visible (i.e. authorised) show in that term's range.

**Comment by hoyes** [comment]
It *should* be based upon the last date of the last authorized show (i.e. as soon as a show appears for a future term, all terms up to and including the one in which that show falls will appear in the diary). But it clearly isn't working quite right! But it's doing something because it's stopping at 2016 not 2030 (see below).

In a possibly over-enthusiastic, over-engineered solution from early-on in v2's development, term dates and week names for v2 are stored in the "time_periods" and "week_names" tables. The idea is that the actual data is stored generically (named periods of time, within which each week may or may not have a name) and not specific to Cambridge nomenclature. In theory, this means that if Cambridge University changes the structure of terms at any point in time, then we can support this for future terms without affecting historical data.

These tables are populated by a console command (https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBackendBundle/Command/TimePeriodsUpdateCommand.php). Initially, this pulled term dates from an Ical feed provided by UCS. Later on though, after inspecting all the entries in the v1 termdates table and all future entries in the ical feed I noticed that they all follow a consistent pattern (e.g. Michaelmas always starts on the Sunday on or before 7th October), so I changed it to simply calculate the term dates directly for a given range of years. These tables are currently populated from 1990 to 2030 (which should cover us until Camdram v3...), but could be trivially extended by changing one line in the script. Equally it's not a big problem if the formula changes or one particular date is wrong because the dates can be manually changed in the DB. But I don't think the dates are going to change sufficiently often to justify a custom interface!

So yes, I made the term date storage really generic, then realised that Cambridge University probably hasn't changed how it decides its term dates for 800 years so we have perhaps just hard coded the formula into Camdram...

**Comment by hoyes** [comment]
Ah, so the 'problem' here is that 'Christmas Vacation 2015/6' is currently defined (for simplicity) to be a 'time period' that occurs just in 2015, even though part of it is in 2016. But then it's showing the year 2016 but Christmas Vacation is only showing for 2015.

It may or may not be related that ETG 2015 spans the end of the year too, so has performances in 2016.

I'm thinking the solution is to display time periods that cross a year boundary for both years (e.g. Christmas Vacation 2015/6 would appear at the bottom of the list for '2015' and at the top of the list for '2016')

**Comment by hoyes** [comment]
Also, as a related issue, the auto-scroll carries on pulling in term dates until 2030 too, whereas it should probably stop after the last known show, or the end of that term or something.

**Comment by philosophicles** [comment]
Is this still a problem? Cannot reproduce currently. Not sure if it could occur again in the future or if we've indirectly fixed it already...

**Comment by CHTJonas** [comment]
I can't reproduce this either so I assume it's been fixed somewhere down the line?

**Comment by philosophicles** [comment]
Let's close this. Not worth spending mental effort on things like this that we can't see right now!
