### ISSUE TITLE
Refinements to shows' Facebook event/page form field

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#339]
I'm not quite sure what the expected behaviour is for the "Facebook event/page" form field (when editing a show) hence this is slightly vague.

Currently (spotted as a result of support ticket 75993) the field appears to function correctly if you just enter the ID part of a facebook URL - e.g. the number '1663900247177258' for that support ticket. I was then able to save the changes and the show's page on Camdram has a link to the correct Facebook event, as expected. 

However, the save action failed (Error 500) with a full URL e.g. 'https://www.facebook.com/events/1663900247177258/' pasted into the field. This generated the following symfony error log: 

> [2015-10-31 14:09:43] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Hoyes\ImageManagerBundle\Twig\Extension\ImageExtension::getImageUrl() must be an instance of Hoyes\ImageManagerBundle\Entity\Image, string given, called in /var/www/camdram/20151027/app/cache/prod/twig/4/2/42e40af5e6e91c69ac50f0c88cf3c8f12140184a86a44bee0ce241bb644f2730.php on line 36 and defined") in "HoyesImageManagerBundle:Form:fields.html.twig"." at /var/www/camdram/20151027/app/cache/prod/classes.php line 5180 {"exception":"[object](Twig_Error_Runtime%28code: 0%29: An exception has been thrown during the rendering of a template %28"Catchable Fatal Error: Argument 1 passed to Hoyes\ImageManagerBundle\Twig\Extension\ImageExtension::getImageUrl%28%29 must be an instance of Hoyes\ImageManagerBundle\Entity\Image, string given, called in /var/www/camdram/20151027/app/cache/prod/twig/4/2/42e40af5e6e91c69ac50f0c88cf3c8f12140184a86a44bee0ce241bb644f2730.php on line 36 and defined"%29 in "HoyesImageManagerBundle:Form:fields.html.twig". at /var/www/camdram/20151027/app/cache/prod/classes.php:5180, Symfony\Component\Debug\Exception\ContextErrorException%28code: 0%29: Catchable Fatal Error: Argument 1 passed to Hoyes\ImageManagerBundle\Twig\Extension\ImageExtension::getImageUrl%28%29 must be an instance of Hoyes\ImageManagerBundle\Entity\Image, string given, called in /var/www/camdram/20151027/app/cache/prod/twig/4/2/42e40af5e6e91c69ac50f0c88cf3c8f12140184a86a44bee0ce241bb644f2730.php on line 36 and defined at /var/www/camdram/20151027/vendor/hoyes/symfony2-image-manager/Hoyes/ImageManagerBundle/Twig/Extension/ImageExtension.php:52)"} []

Don't ask me why the ImageManagerBundle is implicated in this, please :) 

As far as I can see, either we're meant to be capable of handling a full URL pasted in (which makes this a bug), or if we're not trying to handle that, then the form UI isn't giving sufficient hints to allow the user to do the Right Thing. 

So this might be as simple as adding some grey hint text into the form field (like Society has 'Start typing to search') or some explanatory text below the field. Or maybe not :)

**Comment by hoyes** [comment]
The short answer is that is should accept any reasonable identifier for the Facebook page (full URL, ID, page username). Internally, it converts the user input as required and stores the ID (because this is the most useful thing for making API queries etc), but I think it converts this to a URL when showing the edit form (because I thought this would be the most human-friendly form).

Some sort of autocomplete for the search field sounds like a good idea - Facebook provides a search API which could be used for this purpose.

I suspect however that this isn't to do with the Facebook field and is just an image-related thing. It (still...) doesn't handle situations where the image uploaded is in the wrong format or too large very well...

**Comment by philosophicles** [comment]
The show in question does already have an image assigned, but I was able to
update the main Description field without any error. It was only when
trying to input a Facebook url that I got the error 500...

**Comment by hoyes** [comment]
Ah, OK....interesting....

**Comment by ajf58** [comment]
See also support issue 76019.

**Comment by ajf58** [comment]
What is the wrong format?

**Comment by philosophicles** [comment]
@ajf58 is that a question to @hoyes about image formats, or is it a question to me about the original issue topic? Slightly confused :)

**Comment by hoyes** [comment]
"...where the image uploaded is in the wrong format or too large very well..."

If it's about this, I forget the exact details...but the server-side validation of uploading image files is currently lacking some bits. I think the most common failure is when the image is too large for PHP to fit in memory to resize - it just fails silently and it's only detected when it attempts to open the stored image again (that doesn't exist) in order to output it on the page.

This is all covered by #211 though really. It sounds as though there is something else un/semi-related to images going on above that ought to be investigated further

**Comment by charliebruce** [comment]
Thought I'd chip in, as I've just tried editing a society page for the first time and was caught out by this issue. I first tried entering the full URL, and it wasn't initially clear to me that the error was related to the Twitter/Facebook fields. 

For Twitter, the following FAIL:
* `https://twitter.com/girtondrama`
* `http://twitter.com/girtondrama`
The following SUCCEED:
* `@GirtonDrama`
* `GirtonDrama"

For Facebook, the following FAIL:
* `https://www.facebook.com/girtonamateurdramaticssociety/`
The following SUCCEED:
* `@girtonamateurdramaticssociety`
* `girtonamateurdramaticssociety`

I guess the easiest fix is to add some explanation text as to what should be put in each field, or allow it to parse pasted URLs. A full search/autocomplete lookup would be nice but the work-UX improvement tradeoff for that is a lot lower.

**Comment by charliebruce** [comment]
Something wrong here?
https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Form/DataTransformer/FacebookLinkTransformer.php#L73
https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Form/DataTransformer/TwitterLinkTransformer.php#L74

For `https://twitter.com/girtondrama` the regex fails because the URL doesn't feature `www`. In the case of the Facebook link `https://www.facebook.com/girtonamateurdramaticssociety/` it's due to the `maxlength` restriction on the input textbox (it hadn't pasted the complete URL).

**Comment by hoyes** [comment]
This main issues identified here should be fixed in release 20180128.
