### ISSUE TITLE
Camdram Profiles

### ISSUE THREAD

**Issue by luked297** [camdram/camdram#344]
Profile pages for each person should include a brief bio including college, subject and matriculation year (as well as the list of past, present and future shows). There should also be the option to upload a profile picture for each person.

**Comment by philosophicles** [comment]
Hi @luked297 and welcome, thanks for the suggestion. So we know, are you intending to have a go at developing this feature or is it just a suggestion to add to the list? 

My initial thoughts are that this might need to wait until we've refined the link between 'users' and 'people' (itself probably dependent on switching off V1), and then this stuff can be tied to the user login (e.g. inheriting profile picture from Facebook if the user logs in via that service).

**Comment by philosophicles** [comment]
It's also worth noting that 'person' records i.e. lists of involvement with shows, already have a bio type freetext entry area, if the person record has been claimed by a user. E.g. mine (https://www.camdram.net/people/stuart-cuthbertson) has "Pun usually intended". We just have some further design issues to work through in terms of how users claim person records.

**Comment by luked297** [comment]
Hi, this is just a suggestion - I am useless when it comes to technology haha! Good to know that you can already add a brief bio and the fb idea sounds good! :)

**Comment by philosophicles** [comment]
Relevant to #323 possibly.

**Comment by CHTJonas** [comment]
Camdram technically has the functionality for user profiles and profiles images if using an external OAuth login provider, just that it isn't accessible to normal users because we haven't quite sorted out #323. Once a user can claim ownership of a person then this can be fully implemented as @luked297 describes 💯 

As such, I'm going to be bold and close in favour of #323, just so we reduce the number of duplicate tickets.
