### ISSUE TITLE
Add link to view resolved issues in v2

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#353]
Currently https://www.camdram.net/admin/issues only shows open issues, a link to view closed issues (https://www.camdram.net/admin/issues/closed maybe?) would be good.

**Comment by philosophicles** [comment]
That list would be exceptionally long. What's the desired use case for
this?

On the very rare occasions I've needed to look at closed issues, I either
know the issue number (just put it in the url), or I search in phpMyAdmin.

Since this is just for us admins, I'm inclined to say slight fudges like
this are OK...

Stuart

**Comment by dstansby** [comment]
It was mainly in the context of viewing old issues that are brought up here in relation to bugs. I didn't realise that putting the id in the url worked! I might leave this open, but put a future tag on it as a 'nice to have' feature.

**Comment by philosophicles** [comment]
Yeah, when you view any current or past issue, the URL ends in the id.

The change I'd suggest for this use case (if any change happens) is a "go
to issue number:" search box. Or, the fancier implementation would be a
full search box indexing issue numbers, email addresses and subject lines.
(Probably not full email body.)

I personally think either of those would be more useful than a straight
list of resolved issues - does that make sense? However I agree it's a
'nice to have' only, either way. I'm happy without.

**Comment by CHTJonas** [comment]
Closing because the transition to Brimir makes this redundant.
