### ISSUE TITLE
Remove Foundation

### ISSUE THREAD

**Issue by ajf58** [camdram/camdram#356]
We're two versions behind. Let's get up to date.

**Comment by CHTJonas** [comment]
Something to look at along with #424 and #397.

**Comment by hoyes** [comment]
I initially attempted this as part of #397 but it turned out to be quite a lot of work so I reverted.

The version of Foundation we're currently using (4.3.2) is too old to be in the Node package repo so (slightly bizarrely) I left Foundation as a PHP dependency, albeit now packaged by Webpack. When we upgrade, we can move Foundation from composer.json to package.json.

There is also some slightly hacky stuff in webpack.config.js to work around Foundation 4's JS not being ES6 module-compatible which can hopefully go way if we upgrade.

Some stuff I noticed while briefly looking into this:
 * The default max-width is a bit wider than in 4.x.
 * Foundation 6 uses a new "XY grid" by default. It is possible to turn this off (https://foundation.zurb.com/sites/docs/grid.html#importing) and use the "Float grid" instead, which means most of the existing CSS grid markup still works. Might make sense to investigate the XY grid as a separate task.
 * Various other subtle styling changes. Don't think it matters if things change as a result of upgrading, but probably need to visit every/most page and make sure it still looks sensible.

**Comment by GKFX** [comment]
Having worked with it for a little while I’m wondering if Foundation is really going to be useful going forward. The whole notion of columns and `.large-6` etc feels clunky to use. It locks us into thinking of either desktops or narrow phone screens, nothing in between. We could probably be using it better, but equally we could save ourselves the effort and just write modern, more fluid CSS.

The only place it’s really adding value is in the menu bars, which are nice, but could probably be implemented with less than a whole framework. So before we expend too much further effort into an upgrade it might be worth looking at alternative solutions.

**Comment by hoyes** [comment]
No reason to stick with Foundation if the overhead isn't worth the convenience any more. I'll admit I'm not really up to speed on flexbox and other more recent CSS additions, and yea there's already some slightly kludgy stuff going on for the drop-down at the moment.

I wonder whether a hybrid solution might work, whereby we do something custom for the global layout but defer to a framework (not necessarily Foundation) for page-specific stuff inside #content. There might be advantages to retaining a ready-made well-documented toolbox of components when throwing pages together. Or at least if we do something custom here too it's probably worth documenting common use cases on the wiki and going 10% further than is strictly required to ensure e.g. most form field types render with sensible defaults.

**Comment by GKFX** [comment]
https://css-tricks.com/snippets/css/a-guide-to-flexbox/ is a very good reference, I look at it frequently.

Yeah form elements would need a certain amount of work, although for https://github.com/camdram/camdram/commit/4c3d956a81e179496c4c00ce07c764341312bfe0 I’ve already started to deviate from Foundation to get a sensible mobile layout.

As a transition method I thought about creating a framework.scss that replicates a few key classes from Foundation: things like `.right`, `.row`, `.show-for-small`, so that we separate generic rules from specific parts of the layout, and can then document them thoroughly.

**Comment by hoyes** [comment]
All sounds sensible. I'll check out that flexbox link.

Makes sense to reinterpret this ticket as "make Camdram styling good for the next 5 years", whatever that entails, and as you've already started doing. And as always any way of phasing out Foundation incrementally across multiple  releases and avoiding big merges is always good!
