### ISSUE TITLE
Potential show contact page issue

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#383]
The following line is appearing frequently in the error logs:

Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /shows/{...}/contacts": Method Not Allowed (Allow: POST)" at {...}/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 178 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /shows/{...}/contacts\": Method Not Allowed (Allow: POST) at {...}/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:178, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0): at {...}/app/cache/prod/appProdProjectContainerUrlMatcher.php:2399)"} []

Haven't managed to find a repro though

**Comment by philosophicles** [comment]
Are we being crawled by something with possibly-not-good intentions? (But possibly neutral intentions - search engines?) 

I think when a human clicks on the 'Contact the organisers' link from a show (or society/venue) page, it's probably requesting the `slug`/contacts page with `POST` method? And we have some external thing trying to ask for every `slug`/contacts page using `GET`. 

I mention that it could be bad intentions because that would be an excellent page to try sending spam from, if I was a robot looking for HTML forms that I can try sending spam from.

**Comment by philosophicles** [comment]
Ooooh wait - our 'Contact the organisers' links go to `/contact` which is a valid URL. These errors are for `/contacts` (note additional 's') which is never a valid route, I believe.

**Comment by hoyes** [comment]
Looking at the logs these requests seem to be coming from https://www.semrush.com/bot/ - for some reason they seem obsessed with checking these URLs regularly. I'll do a refactor so that this resolves to a 404 instead of 405
