### ISSUE TITLE
Additional /person API endpoints

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#413]
Create additional API endpoint:

1. `/people/slug/shows.json` to get a list of all the shows a person has been involved in,
2. `/people/slug/shows/roles.json` to get a list of roles that person has done in each show.

(2) would return a similar response to eg. https://www.camdram.net/shows/2018-the-pirates-of-penzance-at-the-minack/roles.json

**Comment by philosophicles** [comment]
This is probably not too closely related, but I feel it could possibly have a little overlap with #22 and #55 which were hot (like lava is hot) topics a few years ago. 

Certainly APIs in and of themselves are not the same as a nice easy search UI, but they would of course make it more possible for any third party to independently scrape this data from Camdram and build such a search tool themselves. So we need to be careful to consider whether we'd be OK with consequences like that, if they happened. The end-result dataset that would be obtained by that kind of API scrape would be very powerful, which is why the features discussed in #22 and #55 were so contentious. 

Also, GDPR considerations apply at that point - is that kind of data processing/visibility 'reasonably expected' by the people who've previously consented to have their data on Camdram.

**Comment by CHTJonas** [comment]
I've just taken a look at those two issues you've mentioned. I would agree that I am against adding such functionality to Camdram that allows people to directly search based on roles and you make a good point about others compiling datasets and potentially usurping Camdram in that way. There are definitely considerations as to the extent of data we should offer to third-party applications which we (potentially) have no control over via the API. However if I really wanted I could parse the HTML from the UI scrape data that way rather than by using an API. Granted scraping JSON is about a million times easier than scraping raw HTML, but it's possible.

I should also probably point out that I _believe_ there is (perhaps unfortunately) already a third-party tool which does just this. I have certainly heard of a python script in existence that scrapes the last X years of shows on Camdram and returns a list of people in CSV format that have been listed under role Y for any of those shows. Now this shouldn't be used as motivation in and of itself to make drastic changes but worth bearing in mind maybe.

Using the UI, a user can see all the shows a person has been involved with and all their role(s) in those respective shows. Simplistically considering an API as an extension of the UI for machines I would think the criteria for reasonable expectation would be met but I may be missing a more nuanced approach as to what an API is! 🤷‍♂️

---

Incidentally, I should probably go into the background behind the reason I am suggesting this enhancement. Consider an application such as a hypothetical Cambridge theatre chat-room app. A person logs in and needs to be allowed access to a chatroom for each show they're involved with. Or an application like ticket sales where you might want any member of the theatrical company to check what percentage of the house is sold out. Currently this can only be done using the API if the user on Camdram is also an admin of the show in question. I can think of reasons such as the above where you want to permit show-wide access to something but keep admin of the show on Camdram itself as a separate thing.

**Comment by hoyes** [comment]
* Something very close to what you describe is currently exposed at https://www.camdram.net/people/peter-hoyes/past-roles.json (and other similarly-named endpoints: https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Controller/PersonController.php#L79). It misses out exact role details though and don't see any reason why they have to split like date like that for the API, so probably needs a rethink. It's probably like that as it's also used by the UI.
 * I don't see a way to implement @CHTJonas' use case without doing #323 to prove that an authenticated user "owns" a certain set of show roles. But otherwise yes sounds like a useful thing.
 * As I said before on #55, I still think Camdram should focus its limited time and resources on making the vacancies section better at directing new and existing users towards roles (#159), and providing tools to allow producers to submit more detailed vacancy information. We should make our principles clear in the privacy policy etc (and there's probably more we could do with rate limiting etc for non-authenticated API requests), but if people wanna screen-scrape they're gonna screen-scrape.

**Comment by CHTJonas** [comment]
> In your envisaged use-cases, how would you make the leap from a Camdram `person` (as exposed by this suggested new endpoint), to the user in the third-party app? Would chat-room users have to authenticate to that app via Camdram, and then make use of a link between Camdram `users` and Camdram `people` (#323)? Or something else?

That's a good point actually and one I hadn't really though about (I came up with those examples in the space of a minute) so thanks for the good spot. #323 is definitely a perquisite requirement for this issue.

@hoyes ahhh so the functionality I was actually after already exists, albeit in a slightly different way to what I was thinking. I think it's a little odd that the roles.json endpoint basically returns an array of shows which then have to be individually queried, leading to request amplification. I would propose separating the endpoints slightly so that we have something like the following:

- /people/slug/*-roles.json returns an array of just role objects in JSON form;
- /people/slug/*-shows.json returns an array of show objects in JSON form;

where the asterisks represents one of {past|current|upcoming}. I think that's slightly more logical to my mind if people agree?

On that point Peter, is it worth discussing Camdram requiring _all_ API access to be authenticated with a token? What are our current rate limits?

**Comment by hoyes** [comment]
In the name of keeping things simple, if I were doing this now a single `/people/slugs/roles.json` would probably be sufficient for the API, which would return a list of roles with inline shows. I think I tried a bit too hard to make the GUI and API use the same requests here - we should probably just separate them out in the requests that make most sense for both.

I've just created #416 to discuss API rate limiting (not currently implemented...)
