### ISSUE TITLE
Paginate search results

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#418]
At a quick glance it seems that full search results (not dropdown) are limited to 10 results on a single page. We should look at some form of pagination so users can click through to see more results if they can't find that they're looking for on the first page.

**Comment by philosophicles** [comment]
I'm not sure the limit is as high as 10, at least not consistently...

Searching for `Cambridge Shorts` and going to the full results page (https://www.camdram.net/search?q=Cambridge+Shorts) yields five results. In order, I see:

* June 2018
* October 2016
* May 2017
* March 2017
* May 2016

Ordering aside: there are eight shows in our database with `title = 'Cambridge Shorts'`: two in 2016, four in 2017, two in 2018 (at time of writing). If the "max 10 results per page" was true then I'd expect to see all of these. 

I wonder if the actual limit is related to height of page i.e. cumulative number of lines of text in the shows' descriptions? Or some other factor that varies by show and is counted cumulatively? 

It is also possible that what I'm describing is an unrelated bug, but I'm going to assume it's part of this pagination issue until proven otherwise.

**Comment by CHTJonas** [comment]
I think the limit of 10 might have been from when we were still using Sphinx, but maybe it wasn't 10 at all (I did try a few purposely vague searches that only ever returned 10 so that's what I assumed it was). Maybe it is limited by description or something as you suggest.

**Comment by hoyes** [comment]
The API now supports pagination as a result of work in #445 using a 'limit' and/or 'page' query param, so this just needs some pagination UI adding at some point.
