### ISSUE TITLE
Font sizes erratic on iOS for current master

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#442]
Below is a screenshot of Safari on iOS. I’m not hugely familiar yet with how the site’s styling hangs together so I won’t immediately be investigating this myself; in the meantime let’s not do a release!
![c75a9714-f82e-4893-9ba7-a79f8d8900a0](https://user-images.githubusercontent.com/5357642/42782649-7365b22e-8941-11e8-9009-a26365a74f42.png)
The prod site is fine; this is a recent regression.

**Comment by hoyes** [comment]
Hey - congrats on spotting this. I'm guessing this is because as part of #397 I switched from using http://leafo.github.io/scssphp/ to https://sass-lang.com/libsass to compile our SCSS· Means we're now using an "official" SCSS compiler, which should be a good thing, but I found a couple of other places along the way where I had to tweak the markup.

Unfortunately I cannot repro in Chrome on desktop or Android so looks like this is iOS-specific, but can see it on BrowserStack.

If you'd like to dig deeper, the SCSS files are at https://github.com/camdram/camdram/tree/master/assets/scss and are compiled using instructions at https://github.com/camdram/camdram/wiki/Webpack-setup-guide - let us know if you have trouble. Otherwise I'll pick this up in due course given I broke it...
