### ISSUE TITLE
Double-escaped HTML entity in newsfeed

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#443]
Should be fairly straightforward to fix, the problem is:
![screenshot from 2018-07-16 22-13-02](https://user-images.githubusercontent.com/5357642/42783949-7df129ae-8945-11e8-93c0-586cdeecd5a5.png)
Content of the relevant DB field is
```
This week's improv show GODS &amp; MONSTERS will feature mythology-themed songs by @JessicaTheLaw - have a listen to on… https://t.co/t2fv5dq7Sn
```
The ADC didn't originally tweet an HTML entity (I checked!) so either the Twitter API returns one or we're escaping things before putting them in the DB, and escaping again before displaying them. The actual HTML served is
```
This week&#039;s improv show GODS &amp;amp; MONSTERS will feature mytholog
```

**Comment by hoyes** [comment]
I suspect this is because the Twitter API is returning pre-escaped strings, which we're escaping again. However, taking a few steps back from this, there might be better ways to do this today than pulling the raw data and formatting it ourselves. Facebook and Twitter now both support "oEmbed":
 * https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-oembed.html
 * https://developers.facebook.com/docs/plugins/oembed-endpoints

Hacked-together implementation:
![image](https://user-images.githubusercontent.com/2594055/42830823-7a3fdb30-89e4-11e8-8a90-42c4f8e374f1.png)

Also, there is currently still some code running every 15 minutes to read Facebook posts too. It looks like this stopped working at some point because of https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS . I think our use case is OK, and I submitted an "app review" a week ago but nothing's come back yet. I'm wondering now though whether to just drop Facebook post rendering completely, meaning we could just use https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview.html on society/venue pages. We could keep the Facebook page field for shows/societies/venues, but just render it as a link to the Facebook page.

**Comment by GKFX** [comment]
There's a part of me that vaguely dislikes running Twitter and Facebook's JS on Camdram. I know it's how everything works nowadays but it still seems kind of unnecessary. Since the script-less HTML has lots of suitable classnames in it, it would be interesting to have a go at writing a few lines of CSS to make it look pretty ourselves.

**Comment by hoyes** [comment]
That's a good idea :+1: Yea the Twitter markup is quite verbose and hard to customize once the JS has replaced it all with a iframe.
