### ISSUE TITLE
Person's show credit count can become incorrect

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#447]
Search for e.g. Tiffany Charnley. Reported at #444. This might be something that disappears once the search cache is rebuilt?

**Comment by hoyes** [comment]
I've rebuilt the search index since Tiffany's comment on #444 and it now seems to show the expected number.

The normal listener which updates the search index unfortunately doesn't work for this because it only listens to changes to the "shows" table. There is some stuff in RoleController to explicitly update the show index when a role changes but it clearly isn't working in certain cases.
