### ISSUE TITLE
Expired audition is still shown

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#458]
The show [Oh, What a Lovely War!](https://www.camdram.net/shows/2018-oh-what-a-lovely-war) is still displaying "For auditions contact zhb20@cam.ac.uk by 11:59pm on Fri 29 Jun" despite the deadline being over three weeks ago (according to the user). Additionally, the vacancy link is 404ing.

I imagine there is a stray record in the database somewhere but I thought I'd wait until someone has reviewed the code logic before deleting it.

**Comment by philosophicles** [comment]
Possibly related to #103  - there's a comment there that sounds like the same thing happened with [trade (2015)](https://www.camdram.net/shows/2015-trade), although not visibly wrong any longer.

**Comment by CHTJonas** [comment]
This bug is no longer visible 😢. Guess it's possible someone inadvertently fixed it since July whilst working on something else?

**Comment by hoyes** [comment]
I suspect this bug is still in there but we haven't figured out the recreation steps. At a guess our logic around "scheduled"/"non-scheduled" audition dates is probably flawed somehow.

The DB schema around auditions is a little confused at the moment (for reasons described by @stumo in #103, and probably further complicated by changes I made in v2 that must have made sense at the time...), so I wonder whether we should do something bolder here rather than carrying on re-skinning the same cat as the schema likely hasn't changed since 2004.

Personally, I'd love to head gradually towards a 1st class more generic "advert" concept, whereby each advert would have:
 * A headline
 * Some body text
 * 0 or more audition sessions
 * 0 or more vacant roles (covering anything from musos to techies) 
 * An optionally linked show
 * An optionally linked society
 * An explicit deadline field (which I guess could be automatically determined from audition dates where this makes sense)
The idea is that each show can have multiple adverts and producers are free to batch together sets of vacancies in whatever way makes sense for the show. We could and should discuss the details further (as it touches on #159 #473 #214 #320 etc), but someone could probably uncontroversially refactor auditions along these lines (without changing the UI too much for now) in order to fix this.

**Comment by hoyes** [comment]
I'm kinda interested in finding out people's opinions about Camdram's vacancies features on Friday... I've long thought there's a lot of potential for improvement, but it's a slightly scary thing to change because of how integral the current system has become.

But... I'll have a look the low hanging fruit with auditions this week in a branch, which should hopefully include tidying up the DB schema, improving test coverage (#473) fixing this bug.

**Comment by CHTJonas** [comment]
Agree with everything you've said @hoyes and I like the look of the model you propose above. I think this might be something to work on in a branch and then merge in sometime in the middle of the Winter Vacation when people's use of vacancies is at a minimum.

To be honest, if we publish our intentions I don't think it would be the _worst_ thing in the world if we make breaking changes to the schema and eg. delete all previous vacancy adverts to start afresh. That may make things easier if a migration proves tricky.
