### ISSUE TITLE
Support emails ending up in /var/mail/brimir

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#459]
Legitimate support messages, as well as spam, are ending up in the `/var/mail/brimir` file. We should look at trying to improve spam filtering to prevent this, as well as possibly considering routing spam to `/dev/null` if we are satisfied that this poses no risk. Otherwise the `brimir` user's mbox file will start to grow excessive in size.

**Comment by GKFX** [comment]
So to clarify, emails that end up in /var/mail/brimir don’t appear as support tickets?

As we seem to get a lot of identical spam emails possibly we could filter those senders/message structures to /dev/null directly and then clean up the small amount of remaining spam directly every now and again. I don’t know exactly how easy that is, or whether we should just get a better spam filter from somewhere.

**Comment by CHTJonas** [comment]
From what I can tell that's correct yes.

I believe spam filtering is done upstream by Loho. There's some more basic stuff going on in the Brimir procmail file too.

**Comment by hoyes** [comment]
This was caused by some malformed data in the brimir.users table created by a manual import of v1 support tickets. I'm still a little confused why supposed errors with unrelated rows in table was causing the postfix script to fail, but it now seems to work again so :man_shrugging: 

I've fixed the data and it seems to be working, and manually flushed /var/mail/brimir. For future reference: If an email lands in /var/mail/brimir then it means that procmail failed for some reason, likely because the Brimir REST handler failed

The easiest way I could find to re-pass these message back through procmail was to first use formail to split the spool into one file per message, then run procmail < msgfile for each message you want to import (run as the brimir user)
