### ISSUE TITLE
Add a “Who we are” section to the Development page

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#496]
This would be stored outside the codebase (so either in a config file or the DB). Assuming all involved are happy to publicise their names, it would be nice to say who’s currently contributing to Camdram. I feel like this would make the dev team seem a bit more approachable and human!

I’ll assign the other three currently active people, to give your thoughts and contribute a one-line bio if you would like to be named. Also @alexbrett as you are providing us with free stuff it seems appropriate to give you/Loho a mention too if you would like!

In terms of inactive/former admins, just stating that other people have contributed a large amount of the work might be more appropriate than contacting every past contibutor and asking if they’d like to be named.

**Comment by GKFX** [comment]
Yes, worth raising that now rather than later. Committed to master in the past 6 months (or past 100 commits) would probably be a reasonable way of determining activity. I say 100 commits as well because we might have a quiet period.

Semiautomating makes sense: the whole content of /development could be created by an hourly cron job, rather than the existing approach that 500’s when GitHub is unavailable, and hardcoding our bios into the cron job would be as good a place to store them as any.

**Comment by hoyes** [comment]
It might be helpful to people viewing the page, if it isn't too contentious, to distinguish somehow between people who are actually likely to respond to a query or make a commit in the next week or so from people who've made big contributions in the past but aren't so active at the moment. With the understanding that people can and will unceremoniously drift between the two lists from time to time.

We could maybe go as far as 3 lists...
 * Anyone with >0 commits in the last 6 months
 * People with > 100 commits ever (with scope for also explicitly including others who've made significant contributions in other ways, e.g. as a v1 contributor, doing support or providing hosting services)
 * A name-check of anyone else who's made at least one commit ever

An idea: we could relatively easily add Github OAuth (perhaps only as an option on the Account Settings page), which would allow us to automatically associate the developer profile with a Camdram account, and maybe allow self-service bio editing. From an on-boarding point of view, I kinda like the idea that as soon as someone has a commit accepted, their name will appear alongside everyone else with links to recent commits and recent shows.

I wonder whether, as part of this, we could maybe merge the "Development" and "About Us" pages too, review all the boilerplate text and make it slightly more visually appealing.

**Comment by philosophicles** [comment]
I've no general objections (happy to be named, though not bothered one way or the other). Agree semi-automated is better than manual, for fairness reasons as well as time-saving. v1 did name-check the four main contributors in small print at the bottom of pages, IIRC. 

GDPR-wise, would historic limited-committers expect to see their name pop up on the site? Going forwards, the presence of this on the site Dev page is probably sufficient for implied consent from new committers - though a note on the README might also be wise, "If you commit to this project, your name will appear on <this page>." 

Not so sure about merging 'About' and 'Development' pages though. I think the intended audience of those pages is quite different. Keeping an 'About' link visible on-screen is important for people who land on the site without knowing anything about it. Keeping a 'Development' link as well feels important for the tiny-but-important subset of people for whom that interests them. Without a link like 'Development', people are much more likely to just _assume_ technical participation is closed.

**Comment by CHTJonas** [comment]
Have implemented this is the existing controller. It's super-basic and just grabs the list of the top 10 contributors ordered (I believe) by the number of commits authored by the contributor. It uses real names where possible and usernames otherwise (@stumo & @alexbrett are the only ones affected). Annoyingly it also returns @dependabot-bot in the process...

I have marked this as closed since it's now basically implement but that being said, the development page is really quite slow to load so it would be much better to eg. cron-ify this as George suggests. Another thought would be to cache it with a duration of something like 12 hours - @hoyes would this be possible?

**Comment by hoyes** [comment]
Looks good.

I've tried before to use the techniques described in https://symfony.com/doc/3.4/http_cache.html for the Development page but it still doesn't quite work... I'm probably not far off, and was thinking something like this would be simpler than DB-ifying the data. Could maybe still add a cron to do an HTTP PURGE every 12 hours to avoid users ever having to wait.

The library we're using to target the Github API has Symfony cache integration (https://github.com/KnpLabs/php-github-api#cache-usage) so that's another option.
