### ISSUE TITLE
Rethink role editing UI

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#531]
As discussed on Gitter: https://gitter.im/camdram/development?at=5bfc18d1fa7bbb3fe00986d3

 * Move role editing UI to its own page, likely combined with batch add form
 * Allow editing existing roles
 * Ensure roles look the same for admins and non-admins on main show page, but add edit link(s)
 * Generally create a one-stop-page for everything role related

Possibly related tickets: #372 #110 #323 #413

**Comment by GKFX** [comment]
A thought: roles quite often end up in a fairly random order (or order of recruitment) since users are forced to add to the bottom and jQuery's draggable is a bit fiddly (and non-existent on mobile?).

Allowing roles to be grouped in the editing UI by category (e.g. director/producer, light, sound, set, choreo, but whatever the show wants) would make it easier to organise the role list, especially when working with small screens. I wouldn't want to display the category information publicly though, as that would make the miscellaneous tech roles quite awkward to list. Members of the public would see the roles sorted by group, then sorted by the order within the group, but wouldn't be able to discover what the internal groupings were.

This would presumably be applicable to the cast and band columns too, if you wanted to list the Montagues before the Capulets or the string section before the wind or whatever.
