### ISSUE TITLE
Add confirmation step to 'delete' links

### ISSUE THREAD

**Issue by hoyes** [camdram/camdram#62]
Currently, all 'delete' links instantly delete the entity in question - not ideal if the link's accidentally pressed. Add some sort of confirmation stage, e.g. a popup message or a second page.

'Delete' links are currently only visible to administrators on v2 so probably low priority.

**Comment by CHTJonas** [comment]
On the point of deleting entities from the database, is there a way to actually mark them as deleted and not show them rather than actually DROPping them from the db? In Rails for example you can use [ActsAsParanoid](https://github.com/ActsAsParanoid/acts_as_paranoid) to soft delete in this way and this would be great to do so that we can reverse abuse or careless decisions by show/society admins.

**Comment by hoyes** [comment]
http://atlantic18.github.io/DoctrineExtensions/doc/softdeleteable.html would be the equivalent. The functionality of the "loggable" extension (described on #198) that's already in use may or may not provide a sort of out-of-table equivalent (would need investigating).
