### ISSUE TITLE
Improve person profile page layout

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#660]
Our person / profile pages (e.g. https://www.camdram.net/people/stuart-cuthbertson) perhaps don't scale perfectly if a person has been incredibly active (lots of role entries), especially if their activity has some high-level splits e.g. both acting and backstage, or acting and band, or photography and backstage. 

In those situations some users might like to have more flexibility over how their page displays. E.g. to change the sort order, or to group roles in some way (e.g. separating acting from backstage from band). 

There are a lot of ways this could go, so this is initially just for brainstorming and idea collection.

_(Inspired by a webteam email thread, wherein first mentioned by @GKFX.)_

**Comment by philosophicles** [comment]
One design approach idea I had was adding a sidebar, like on https://www.camdram.net/vacancies/auditions, that simply separates roles based on whether they're Cast, Crew, or Band (a split we already understand on a data level), with a fourth 'All' option as default. 

This would probably be relatively straightforward to implement across the board. 

Within each section, roles would then still be sorted chronologically.

**Comment by GKFX** [comment]
Adding a sidebar (`.sidenav`, which goes across the top on mobile) would be one approach to the UI; a `.tabbed-container` is the other approach.

For users who wish to classify their roles further, we could add a `tag` column to the roles table, which would be editable by the person named rather than by the show editor. Any role tagged goes into a tab of that name, while any role where `tag` is null would be classified under that name.
