### ISSUE TITLE
Address multiple issues in ExternalUser entity

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#699]
Not really a bug or enhancement, but the `ExternalUser` entity and associated table in the database needs a bit of TLC/refactoring. Some basic tasks that were discussed in Gitter on [2019-07-03](https://gitter.im/camdram/development?at=5d1cea89dd5b167204eaa49d):

- [ ] Scan the `acts_external_users` table and fix all `user_id` fields where the email address matches a record in `acts_users`.
- [ ] Delete all records in `acts_external_users` where `user_id` is `NULL`.
- [ ] Make the `acts_external_users.user_id` field non-nullable.
- [ ] Drop the `acts_external_users.person_id` field and remove the relationship in the PHP.

**Comment by GKFX** [comment]
External user entities with null `user_id` are created when a user logs in with an external service but doesn't complete signup, explaining why they continue to be created. This is partly because the screen the user reaches has not been updated for use without a password, so the intended flow

user logs in with new external provider → user links this to their existing account → user is now logged in and has a permanent new login provider

is not possible. I'm thinking now that we should just delete these once they are ~48 hours old as by that point they are obsolete—if the user's tab is still open at that point and they attempt to continue, they should appreciate that the request has "timed out" in some way.
