### ISSUE TITLE
Prevent choosing date ranges that end before they start

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#705]
The date range fields need some additional validation to prevent people choosing end dates that are before the start dates.

<img width="855" alt="Screenshot 2019-07-14 at 17 05 17" src="https://user-images.githubusercontent.com/17813061/61186165-1e78a000-a65a-11e9-8fec-9c3cfcac5db0.png">

**Comment by CHTJonas** [comment]
We might also consider preventing users from creating events that are more than a year in the future or 6 months in the past as an additional layer of accidental data-entry validation?

**Comment by philosophicles** [comment]
I think we want to welcome retrospective addition of old events - it's rare but we shouldn't prevent it. 

So I'd advise against outright prevention of creating very old events, and more towards some kind of visual warning that appears - "This listing is over a year old. Are you sure the dates are correct?"

To be honest, that warning would probably be justified for anything over about a month in the past!

As for the future - I can imagine touring theatre productions knowing their dates a bit more than a year in the future. It seems unlikely we'd get anything intentional over 18 months, though. A hard prevention at 18 months in the future might be appropriate, with a warning for anything over 6 months maybe?
