### ISSUE TITLE
Raven for Life log-in issues

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#742]
The user who opened [ticket 2193](https://support.camdram.net/tickets/2193) claims to have been unable to log in to Camdram with their Raven account, despite being the fact that they have a Raven account registered with us. I'm still a student so I don't have access to such a Raven account - would it be possible for e.g. @CHTJonas to let me know if this is something which should work.

**Comment by CHTJonas** [comment]
This is very strange - login with Raven for life has been working for me as long as I’ve had it. Might be worth checking exactly how they’re logging in to Raven; I’m putting my CRSid + password into the login form rather than a cam or alumni email address + password.

Failing that, my only suggestion would be to delete their Raven account manually from the DB, get them to a new login and then do a user merge on the resulting newly-created account.

**Comment by GKFX** [comment]
I'll leave that ticket as-is now since they regained access to their account anyway - good to know that RfL generally works though.
