### ISSUE TITLE
Email Builder

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#79]
I'm going to have a quick bash at writing an email builder, as I don't think anyone else is working on that yet?

**Comment by hoyes** [comment]
I'm thinking about tackling this is a slightly different way. I'm wondering about implementing this in a separate repository (hosted at emailbuilder.camdram.net or something), and using the Camdram API. The flow would be something like:
 * Log in using Camdram (in a similar way to https://camdram-api-demo.herokuapp.com/)
 * Only authorize users which are admins for CUADC on Camdram (an additional/separate whitelist of Camdram users could be used if this isn't sufficient)
 * Provide a similar UI to old.camdram.net, which uses data consumed from /vacancies/auditions.json etc

The motivation is that (IMO) this isn't a 'core' Camdram feature as the interface is only used by a small number of people, and it would work well as a standalone 'app' as it uses a well-defined subset of Camdram's data. To be clear, this would still be fully supported by Camdram devs (and would be kept under the 'camdram' Github organisation), but the hope is that by keeping the code separate it might be easier for CUADC to make small changes (e.g. aesthetic changes to templates) directly rather than having to understand the rest of the Camdram repo. It also solves the problem of deciding where to put the 'Email Builder' link!

Additionally, the goalposts seemed to have moved slightly in terms of the format of the e-mail since stumo's work. AFAIK the e-mails sent out have now reverted to the original format, so I propose that for this ticket we implement like-for-like functionality, without precluding any changes in the future.

Thoughts?

**Comment by stumo** [comment]
I can certainly see the sense in that - in fact, given that everything in
the adverts should be publicly visible on camdram anyway, I don't know that
the login is needed for access to our DB data (although it seems a good way
of protecting the linked application from being too easy to log into)

**Comment by philosophicles** [comment]
I also like the idea. It could act as something of a demonstration of the API in practice, and perhaps show other people what is possible so other interesting projects might emerge (in years to come...).
