### ISSUE TITLE
Default install command does not create CSP hash database

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#832]
The `composer create-project` shell one-liner does not create the required `csp_hashes.txt` file and so navigating to a local web page raises a `ContextErrorException`.

The exact message is:

```
Warning: file_get_contents(~camdram/src/Acts/CamdramBundle/EventListener/../../../../web/build/csp_hashes.txt): failed to open stream: No such file or directory
```

**Comment by GKFX** [comment]
What happens if you then create it but don’t do anything else? `echo -n "'unsafe-inline'" > web/build/csp_hashes.txt` is the allow-all policy. Is there any CSS or JS loaded?

Running yarn should be a requirement to get the site up as without it there’s no scripts or styles, and running yarn should always generate the hashes.

**Comment by hoyes** [comment]
I've just made the `camdram:assets:download` command (which is run as part of `create-project`) fetch the csp_hashes.txt file from master.dev.camdram.net.
