### ISSUE TITLE
Cannot create new society

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#942]
Logged in as admin, fill in form https://www.camdram.net/societies/new - just the 2 required fields, click Create. 

I am redirected to https://www.camdram.net/venues and I see the "New Venue" form, rather than the map. Refreshing on this page shows me the map as expected. Inspecting the DB shows no new record in the `acts_societies` table (nor in `acts_venues`). 

Two weirdnesses here: 

1. Society not created - seems like a routing issue as I don't get any actual error. No symfony error logged that I can see. 
2. Seeing the New Venue form at `/venues` when it should be at `/venues/new`. (Maybe related but not certain?)

**Comment by GKFX** [comment]
Part 1 is fixed in b2f305296e00bef6b01fde27f23e0b39d12e563. Part 2 is the correct behaviour; you submitted a mis-formed POST request to `/venues` and got the New Venue form as a response. The intended use case for that is that the user goes to /venues/new, fills in the form wrong, POSTs it to /venues and gets their form returned to them for corrections.
