### ISSUE TITLE
Remove the show count from search result dropdown

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#946]
[Support ticket #2446](http://support.camdram.net/tickets/2446)

A suggestion that's come from a user is that we remove the counter in the search result dropdown that tells a user how many shows a particular person has been involved with. This would be done in order to focus on individual shows themselves rather than the number of shows overall, to help mitigate unhealthy competitiveness and to "enjoy theatre for its own sake".

How do we feel about this as a dev team? Speaking for myself, I could be amenable to moving the counter from the search results dropdown to a part of each person's public profile page.

**Comment by GKFX** [comment]
I would support this and it was with this in mind that I added additional context to the search dropdown recently, giving the timespan over which a person has been active rather than just their most recent show.

I think it would look better to put a count on each section of the person page (current/future/past) in the header with `.split-header` rather than an overall total.

**Comment by philosophicles** [comment]
No strong feelings either way here - IIRC the count of shows was only ever intended to disambiguate people with the same name. Certainly, driving competitiveness was never the intention.

I (perhaps unnecessarily) feel the need to point out that unhealthy attitudes towards competition or judging oneself against others, will find ways to persist regardless of changes like this. This might not be as much of a fix for the _real_ problem as the user imagines. But that's not an argument for not doing it.
